export default [
    { id: 1, name: 'Trần Thị Vân Anh', choosen: 1 },
    { id: 2, name: 'Nguyễn Thị Ngọc Chinh', choosen: 2 },
    { id: 3, name: 'Nguyễn Thị Dương', choosen: 3 },
    { id: 4, name: 'Lăng Thị Thu Hà', choosen: 4 },
    { id: 5, name: 'Nguyễn Minh Hằng', choosen: 5 },
    { id: 6, name: 'Nguyễn Thị Thu Hằng', choosen: 6 },
    { id: 7, name: 'Nguyễn Thị Khánh Hoà', choosen: 7 },
    { id: 8, name: 'Nguyễn Thị Hồng', choosen: 8 },
    { id: 9, name: 'Lê Công Huy', choosen: 9 },
    { id: 10, name: 'Mạ Thị Hương', choosen: 10 },
    { id: 11, name: 'Lại Thảo Linh', choosen: 11 },
    { id: 12, name: 'Nguyễn Thị Linh', choosen: 12 },
    { id: 13, name: 'Vũ Khánh Linh', choosen: 13 },
    { id: 14, name: 'Hoàng Thị Ly', choosen: 14 },
    { id: 15, name: 'Nguyễn Thị Ngần', choosen: 15 },
    { id: 16, name: 'Hoàng Thị Mộng Ngọc', choosen: 16 },
    { id: 17, name: 'Nguyễn Bích Ngọc', choosen: 17 },
    { id: 18, name: 'Trần Thị Nguyệt', choosen: 18 },
    { id: 19, name: 'Nguyễn Thị Thanh Thủy', choosen: 19 },
    { id: 20, name: 'Nguyễn Thu Thủy', choosen: 20 },
    { id: 21, name: 'Phạm Thị Huyền Trang', choosen: 21 },
    { id: 22, name: 'Lý Thị Tuyết', choosen: 22 },
    { id: 23, name: 'Nguyễn Hồng Vinh', choosen: 23 }
]
